# Generated by Django 3.0.8 on 2020-11-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personal_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=3)),
                ('email', models.CharField(max_length=15)),
                ('cv', models.CharField(max_length=15)),
            ],
        ),
    ]
