# Generated by Django 4.0.1 on 2022-02-02 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=3)),
                ('mobile', models.CharField(max_length=15)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_records.section')),
            ],
        ),
    ]
